// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: pb/wrapping.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Wrapping struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Callback bool   `protobuf:"varint,2,opt,name=callback,proto3" json:"callback,omitempty"`
	Body     []byte `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *Wrapping) Reset() {
	*x = Wrapping{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_wrapping_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Wrapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wrapping) ProtoMessage() {}

func (x *Wrapping) ProtoReflect() protoreflect.Message {
	mi := &file_pb_wrapping_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wrapping.ProtoReflect.Descriptor instead.
func (*Wrapping) Descriptor() ([]byte, []int) {
	return file_pb_wrapping_proto_rawDescGZIP(), []int{0}
}

func (x *Wrapping) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Wrapping) GetCallback() bool {
	if x != nil {
		return x.Callback
	}
	return false
}

func (x *Wrapping) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

var File_pb_wrapping_proto protoreflect.FileDescriptor

var file_pb_wrapping_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x62, 0x2f, 0x77, 0x72, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x61, 0x69, 0x6e, 0x22, 0x4a, 0x0a, 0x08, 0x57, 0x72, 0x61,
	0x70, 0x70, 0x69, 0x6e, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x63, 0x61, 0x6c, 0x6c, 0x62, 0x61, 0x63,
	0x6b, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x42, 0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_wrapping_proto_rawDescOnce sync.Once
	file_pb_wrapping_proto_rawDescData = file_pb_wrapping_proto_rawDesc
)

func file_pb_wrapping_proto_rawDescGZIP() []byte {
	file_pb_wrapping_proto_rawDescOnce.Do(func() {
		file_pb_wrapping_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_wrapping_proto_rawDescData)
	})
	return file_pb_wrapping_proto_rawDescData
}

var file_pb_wrapping_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_pb_wrapping_proto_goTypes = []interface{}{
	(*Wrapping)(nil), // 0: main.Wrapping
}
var file_pb_wrapping_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pb_wrapping_proto_init() }
func file_pb_wrapping_proto_init() {
	if File_pb_wrapping_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_wrapping_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Wrapping); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_wrapping_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pb_wrapping_proto_goTypes,
		DependencyIndexes: file_pb_wrapping_proto_depIdxs,
		MessageInfos:      file_pb_wrapping_proto_msgTypes,
	}.Build()
	File_pb_wrapping_proto = out.File
	file_pb_wrapping_proto_rawDesc = nil
	file_pb_wrapping_proto_goTypes = nil
	file_pb_wrapping_proto_depIdxs = nil
}
